### ISSUE TITLE
Code Issue

### ISSUE THREAD

**Issue by M-Aitisam** [NeshOfficial/Deepmine-Tec#10]
The current codebase fails to run due to unresolved dependencies. The dependencies are not listed in the documentation, making it difficult to install them correctly. Additionally, the code throws errors when trying to execute certain functions.

**Comment by Muhammad-Awab** [comment]
The issue was resolved by identifying the missing dependencies and adding them to the build.config file. Updated the documentation with specific installation steps: npm install --config build.config. The code is now executing without errors, and all functions are working correctly. Please update your local environment by pulling the latest changes and following the revised installation instructions.
