### ISSUE TITLE
Throwing me error for following location BreadcrumbsDeepmine-Tec/include/mujoco /mjmodel.h

### ISSUE THREAD

**Issue by M-Aitisam** [NeshOfficial/Deepmine-Tec#9]
Hi team, In the Deepmine-Tec/include/mujoco/mjmodel.h file, the code snippet includes several geometry constants such as mjGEOM_ARROW, mjGEOM_LINE, and mjGEOM_TRIANGLE. However, there appears to be an issue with the definition or usage of these constants. Could someone review the definitions to ensure they are correctly implemented and used? Additionally, check for any missing or inconsistent constants in the file.Thanks

**Comment by rehan985** [comment]
Hey M-Aitsam, appreaciate your energy for looking our prjectts with great interest and letting us your issues off and on. The correct soloution to your problem is simply upgrade your system, then try for this. Because in most of the cases it automatically picks up the outdated pacages so that's the real case.
If you're using debian family OS;
CLI : sudo apt get upgrade
